baseURL = "https://GCoiffier.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Guillaume Coiffier"
theme = "hello-friend-ng"

[params]
disableReadOtherPosts = false
enableSharingButtons = true
enableGlobalLanguageMenu = true
enableEmoji = true
home_css = "css/home.css"
publication_css = "css/publication.css"
blog_css = "css/blog.css"
figure_css = "css/figure.css"
cv_css = "css/cv.css"
math = false # enable math by adding math=true in frontmatter
toc = false # enable table of content at the beginning of a post by adding toc=true in frontmatter

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
    table = true
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2


[[params.social]]
  name = "github"
  url = "https://github.com/GCoiffier"
  
[[params.social]]
  name = "mastodon"
  url = "https://social.sciences.re/@GCoiffier"

[[params.social]]
  name = "googlescholar"
  url = "https://scholar.google.fr/citations?user=g1giJ6sAAAAJ&hl"

[[params.social]]
  name = "orcid"
  url = "https://orcid.org/0000-0001-5324-5122"

[params.portrait]
  path     = "img/me.jpg"
  alt      = "Photo of me by ©l'oeilcreatif"
  maxWidth = "300px"

[languages]
  [languages.en]
    title = "Guillaume Coiffier - Personal Website"
    languageCode = "en-us"
    languageName = 'English'
    weight = 2

  [languages.fr]
    title = "Guillaume Coiffier - Site Personnel"
    languageCode = "fr-FR"
    languageName = 'Français'
    weight = 1

[[menu.main]]
identifier = "cv"
name = "CV"
url = "/cv"
weight = 10

[[menu.main]]
identifier = "publis"
name = "Publications"
url = "/publications"
weight = 20

[[menu.main]]
identifier = "blog"
name = "Misc"
url = "/blog"
weight = 30
